spring.application.name=curriculum-todo-spring-answer
server.port=8000

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/curriculum_todo_spring}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
